### ISSUE TITLE
Khmer Unicode is not rendering properly

### ISSUE THREAD

**Issue by chhinsras** [VahidN/iTextSharp.LGPLv2.Core#61] opened 2020-10-09 07:31 UTC
I follow the step to create pdf succesfully and dispalyed the khmer text . but not proper rendering. And Lost English text.

![Screen Shot 2020-10-09 at 2 31 10 PM](https://user-images.githubusercontent.com/31751665/95555496-16193b80-0a3c-11eb-9e74-6ad0d100f6ea.png)

  ```
private Font GetFont(string fontNameWithExtension, int fontSize = 12)
        {
            // string fontLocation = $"{Directory.GetCurrentDirectory()}{"/wwwwroot/fonts/" + fontNameWithExtension}";
            string path = _webHostEnviroment.WebRootPath + "/fonts";
            string fontPath = Path.Combine(path, fontNameWithExtension);

            iTextSharp.text.FontFactory.Register(fontPath);

            BaseFont bf = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font f = new Font(bf, fontSize);
            


            return f;
        }
```

**Comment by VahidN** [comment] 2020-10-09 07:40
> And Lost English text

It's duplicate of https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/58
It means your font is incomplete & doesn't have the English characters glyphs. In this case you should use the `FontSelector`.

```C#
FontFactory.Register("c:\\windows\\fonts\\font-1.ttf");
Font bZar = FontFactory.GetFont("font 1 name here", BaseFont.IDENTITY_H);

FontFactory.Register("c:\\windows\\fonts\\tahoma.ttf");
Font tahoma = FontFactory.GetFont("tahoma", BaseFont.IDENTITY_H);

FontSelector fontSelector = new FontSelector();
fontSelector.AddFont(bZar);
fontSelector.AddFont(tahoma);

var phrase = fontSelector.Process("your text here ....");
```

**Closed by VahidN** 2020-10-09 07:40 UTC

**Comment by chhinsras** [comment] 2020-10-09 09:11
I followed this. then it is only rendering english, not khmer font any more

**Comment by VahidN** [comment] 2020-10-09 09:40
You should add at least 2 fonts to the `FontSelector`, one with the English chars glyphs and one with the Khmer chars glyphs.
And before that, you can open these fonts with the `character map` application of Windows to see what are in them. Do they have enough glyphs or not.

**Comment by chhinsras** [comment] 2020-10-10 07:28
now it is only rendering english.

**Comment by chhinsras** [comment] 2020-10-10 07:44
this is my reop. can you check it. https://github.com/chhinsras/AspNetiTextSharp/tree/master
