### ISSUE TITLE
Not resolved iTextSharp.text.pdf.parser reference 

### ISSUE THREAD

**Issue by prasadpawale** [VahidN/iTextSharp.LGPLv2.Core#10] opened 2017-05-08 10:43 UTC
I am using .NET Core framework and used iTextSharp.LGPLv2.Core 1.2.6 package for PDF operations.
I want to use PdfTextExtractor for some text replacement, but says namespace not found.

**Comment by VahidN** [comment] 2017-05-08 13:04
It's duplicate of https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/7 and https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/3

**Closed by VahidN** 2017-05-08 13:04 UTC
